import type { H3Event } from "h3"

export interface UploadFileDescriptor {
  name: string
  size: number
  mimeType: string
}

export type AuthorizeOp =
  | { type: "presign-upload"; file: UploadFileDescriptor }
  | { type: "presign-download"; key: string }
  | { type: "delete"; key: string }
  | { type: "direct-upload"; file: UploadFileDescriptor }
  | { type: "list"; prefix?: string }

export interface AuthorizeContext {
  userId?: string
  [key: string]: unknown
}

export interface ServerHookContext {
  event: H3Event
  auth: AuthorizeContext
}

/**
 * Result returned by a storage adapter's presignUpload.
 * The client uses `uploadUrl` to PUT the file, then surfaces `publicUrl` as the file's URL.
 * `fileId` is the key the storage adapter resolved for the file (driven by keyStrategy).
 */
export interface PresignUploadResult {
  uploadUrl: string
  publicUrl: string
  fileId: string
  /** Optional form fields for POST-style presigned uploads (e.g. S3 POST policy). */
  fields?: Record<string, string>
  /** Extra request headers the client must send with the PUT (e.g. Azure's `x-ms-blob-type: BlockBlob`). */
  headers?: Record<string, string>
}

export interface PresignedFileInput extends UploadFileDescriptor {
  /** Caller-resolved id (typically generated by useUploadKit). Storage adapter may pass this through keyStrategy. */
  fileId: string
}

/**
 * Server-side storage adapter contract.
 * Adapters wrap a cloud SDK and expose the operations the auto-mounted endpoints need.
 * Only `presignUpload` is required for v0.2 / #183; other methods land with #184/#185.
 */
export interface StorageAdapter {
  id: string
  presignUpload: (input: PresignedFileInput, ctx: ServerHookContext) => Promise<PresignUploadResult>
  presignDownload?: (key: string, ctx: ServerHookContext) => Promise<{ downloadUrl: string }>
  delete?: (key: string, ctx: ServerHookContext) => Promise<void>
  put?: (input: { key: string; body: unknown; contentType?: string }, ctx: ServerHookContext) => Promise<{ publicUrl: string }>
  list?: (prefix: string | undefined, ctx: ServerHookContext) => Promise<Array<{ key: string; size: number }>>
  /**
   * Resolve the final storage key for a given file descriptor using the adapter's keyStrategy.
   * Used by the /direct handler so direct uploads share the same key resolution as presigned uploads.
   */
  resolveKey?: (input: PresignedFileInput) => string
}

/**
 * Server-side validator. Throws to reject; returning normally accepts.
 * Use `createError({ statusCode: 4xx, message })` to control the HTTP response.
 */
export type ServerValidator = (file: UploadFileDescriptor, ctx: ServerHookContext) => void | Promise<void>

export interface UploadServerConfig {
  storage?: StorageAdapter
  authorize?: (event: H3Event, op: AuthorizeOp) => AuthorizeContext | Promise<AuthorizeContext>
  validators?: ServerValidator[]
  /**
   * Maximum request body size (in bytes) accepted by the `/direct` upload endpoint.
   * Enforced against the `Content-Length` header before the body is read into memory,
   * so authorize/validators never see oversized requests. Rely on an upstream
   * proxy/CDN request-size cap for chunked transfer encoding, which has no Content-Length.
   */
  maxBodySize?: number
  hooks?: {
    beforePresign?: (file: UploadFileDescriptor, ctx: ServerHookContext) => void | Promise<void>
    afterUpload?: (file: UploadFileDescriptor, ctx: ServerHookContext) => void | Promise<void>
    beforeDelete?: (key: string, ctx: ServerHookContext) => void | Promise<void>
  }
}

export interface ServerUpload {
  presignUpload: (file: PresignedFileInput) => Promise<PresignUploadResult>
  presignDownload: (key: string) => Promise<{ downloadUrl: string }>
  delete: (key: string) => Promise<void>
  put: (input: { key: string; body: unknown; contentType?: string }) => Promise<{ publicUrl: string }>
  list: (prefix?: string) => Promise<Array<{ key: string; size: number }>>
}
